### ISSUE TITLE
Connections.Response Overloading and In Skill Purchasing. 

### ISSUE THREAD

**Issue by aadupirn** [stoiveyp/Alexa.NET.InSkillPricing#10]
The response type "Connections.Response" is used in a lot more places than In Skill Purchasing. For the alexa amzonpay integration its used for a couple different requests. The API docs are [here](https://developer.amazon.com/docs/amazon-pay/amazon-pay-apis-for-alexa.html#charge). The responses that alexa makes to the Setup and Charge steps are both using Connections.Response. I'm adding models following this pattern for an amazonpay-alexa integration and am happy to pr them here though I'm not sure if this is the right repo for them. Is this project just intended for in app purchasing and such or all alexa purchasing integrations? The name makes it a little unclear to me.

**Comment by stoiveyp** [comment]
Hi @aadupirn - Amazon Pay and In-Skill Purchasing are different enough that I don't feel putting them into the same repo is desirable. It is a shame that there's re-use of some of the object type identifiers, but I still think it would be better for skill developers to keep them separate.

Initially I left this particular journey out of the support I wrote with all the Alexa.NET extensions as the process required becoming an Amazon Pay merchant - which wasn't something I was prepared to do, but it would be great if you were able to provide that for our users.

Thanks for your enquiry - let me know if there's anything else I can help with

Steven
