### ISSUE TITLE
Add Request Handler Support - Readme.md

### ISSUE THREAD

**Issue by jbiams77** [stoiveyp/Alexa.NET.InSkillPricing#13]
For adding the Request Handler support, your markdown suggest using 
``` ConnectionResponseHandler.AddToRequestConverter(); ```

when it should be 

``` ConnectionRequestHandler.AddToRequestConverter();```

Thanks for making this library, super helpful!

**Comment by stoiveyp** [comment]
Thanks for the catch - doc has been updated 👍
