### ISSUE TITLE
Purchase Result missing "PENDING_PURCHASE"

### ISSUE THREAD

**Issue by jbiams77** [stoiveyp/Alexa.NET.InSkillPricing#14]
In addition to the Purchase Result in 'PurchaseResult.cs': 

```
public const string Accepted = "ACCEPTED";
public const string Declined = "DECLINED";
public const string AlreadyPurchased = "ALREADY_PURCHASED";
public const string Error = "ERROR";
```

There is a "PENDING_PURCHASE" option. This occurs in a kids skill where a parent needs approval. The payload is returned as a ConnectionResponse (example from my payload):

```
"request": {
		"type": "Connections.Response",
		"requestId": "amzn1.echo-api.request.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"timestamp": "2021-04-29T18:25:34Z",
		"locale": "en-US",
		"status": {
			"code": "200",
			"message": "OK"
		},
		"name": "Upsell",
		"payload": {
			"purchaseResult": "PENDING_PURCHASE",
			"productId": "amzn1.echo-api.request.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
		},
		"token": "correlationToken"
	}
```

**Comment by stoiveyp** [comment]
Thanks for raising this @jbiams77 - I'll try and get this status added in the next few hours 👍

**Comment by jbiams77** [comment]
No problem, thanks for the library, it's been very useful!

**Comment by stoiveyp** [comment]
The pending purchase status has been added in v3.0.1 which has just been published
I haven't looked at kids skills for my own work, but it appears this library could do with an update - I'll make time over the weekend to take a proper look. Thanks again
